language: ruby # don't install any environment
cache: bundler

sudo: false
rvm:
  - 2.2
before_install:
  - bundle update
script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "XSJd5HPKIzdq"
  - COMMIT_AUTHOR_EMAIL: "denver@denverprophit.us"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true

branches:
  only:
  - master
  
